import 'package:share_plus/share_plus.dart';
import 'package:emily_marathon_split_calculator/bloc/bloc_state.dart';

class ExportUtils {
  static Future<void> exportSplits(RaceSettingsState state) async {
    if (state.splitTimes.isEmpty) {
      return;
    }

    final paceLabel = state.useMetricUnits ? 'km' : 'mi';

    final buffer = StringBuffer();
    buffer.writeln("Emily's Race Split Calculator");
    buffer.writeln("=============================");
    buffer.writeln();
    buffer.writeln("Race: ${state.raceDistance}");
    buffer.writeln(
        "Pace: ${state.paceMinutes}:${state.paceSeconds.toString().padLeft(2, '0')} per $paceLabel");
    buffer.writeln(
        "Start Time: ${state.startTime.hour.toString().padLeft(2, '0')}:${state.startTime.minute.toString().padLeft(2, '0')}");
    buffer.writeln();
    buffer.writeln("Split Times:");
    buffer.writeln("------------");

    for (final split in state.splitTimes) {
      buffer.writeln(split['text']);
    }

    buffer.writeln();
    buffer.writeln("Generated by Emily's Race Split Calculator");

    await Share.share(buffer.toString(),
        subject: 'Race Split Times - ${state.raceDistance}');
  }
}
